#pragma once

#define ABELIAN_KEY_SPACE				32
#define ABELIAN_KEY_APOSTROPHE			39
#define ABELIAN_KEY_COMMA				44
#define ABELIAN_KEY_MINUS				45
#define ABELIAN_KEY_PERIOD				46
#define ABELIAN_KEY_SLASH				47
#define ABELIAN_KEY_0					48
#define ABELIAN_KEY_1					49
#define ABELIAN_KEY_2					50
#define ABELIAN_KEY_3					51
#define ABELIAN_KEY_4					52
#define ABELIAN_KEY_5					53
#define ABELIAN_KEY_6					54
#define ABELIAN_KEY_7					55
#define ABELIAN_KEY_8					56
#define ABELIAN_KEY_9					57
#define ABELIAN_KEY_SEMICOLON			59
#define ABELIAN_KEY_EQUAL				61
#define ABELIAN_KEY_A					65
#define ABELIAN_KEY_B					66
#define ABELIAN_KEY_C					67
#define ABELIAN_KEY_D					68
#define ABELIAN_KEY_E					69
#define ABELIAN_KEY_F					70
#define ABELIAN_KEY_G					71
#define ABELIAN_KEY_H					72
#define ABELIAN_KEY_I					73
#define ABELIAN_KEY_J					74
#define ABELIAN_KEY_K					75
#define ABELIAN_KEY_L					76
#define ABELIAN_KEY_M					77
#define ABELIAN_KEY_N					78
#define ABELIAN_KEY_O					79
#define ABELIAN_KEY_P					80
#define ABELIAN_KEY_Q					81
#define ABELIAN_KEY_R					82
#define ABELIAN_KEY_S					83
#define ABELIAN_KEY_T					84
#define ABELIAN_KEY_U					85
#define ABELIAN_KEY_V					86
#define ABELIAN_KEY_W					87
#define ABELIAN_KEY_X					88
#define ABELIAN_KEY_Y					89
#define ABELIAN_KEY_Z					90
#define ABELIAN_KEY_LEFT_BRACKET   		91 /* [ */
#define ABELIAN_KEY_BACKSLASH   		92 /* \ */
#define ABELIAN_KEY_RIGHT_BRACKET   	93 /* ] */
#define ABELIAN_KEY_GRAVE_ACCENT   		96 /* ` */
#define ABELIAN_KEY_WORLD_1  			161 /* non-US #1 */
#define ABELIAN_KEY_WORLD_2  			162 /* non-US #2 */
#define ABELIAN_KEY_ESCAPE   			256
#define ABELIAN_KEY_ENTER   			257
#define ABELIAN_KEY_TAB   				258
#define ABELIAN_KEY_BACKSPACE   		259
#define ABELIAN_KEY_INSERT   			260
#define ABELIAN_KEY_DELETE   			261
#define ABELIAN_KEY_RIGHT   			262
#define ABELIAN_KEY_LEFT   				263
#define ABELIAN_KEY_DOWN   				264
#define ABELIAN_KEY_UP   				265
#define ABELIAN_KEY_PAGE_UP   			266
#define ABELIAN_KEY_PAGE_DOWN   		267
#define ABELIAN_KEY_HOME   				268
#define ABELIAN_KEY_END  				269
#define ABELIAN_KEY_CAPS_LOCK   		280
#define ABELIAN_KEY_SCROLL_LOCK   		281
#define ABELIAN_KEY_NUM_LOCK   			282
#define ABELIAN_KEY_PRINT_SCREEN   		283
#define ABELIAN_KEY_PAUSE   			284
#define ABELIAN_KEY_F1   				290
#define ABELIAN_KEY_F2   				291
#define ABELIAN_KEY_F3   				292
#define ABELIAN_KEY_F4   				293
#define ABELIAN_KEY_F5   				294
#define ABELIAN_KEY_F6   				295
#define ABELIAN_KEY_F7   				296
#define ABELIAN_KEY_F8   				297
#define ABELIAN_KEY_F9   				298
#define ABELIAN_KEY_F10   				299
#define ABELIAN_KEY_F11   				300
#define ABELIAN_KEY_F12   				301
#define ABELIAN_KEY_F13   				302
#define ABELIAN_KEY_F14   				303
#define ABELIAN_KEY_F15   				304
#define ABELIAN_KEY_F16   				305
#define ABELIAN_KEY_F17   				306
#define ABELIAN_KEY_F18   				307
#define ABELIAN_KEY_F19   				308
#define ABELIAN_KEY_F20   				309
#define ABELIAN_KEY_F21   				310
#define ABELIAN_KEY_F22   				311
#define ABELIAN_KEY_F23   				312
#define ABELIAN_KEY_F24   				313
#define ABELIAN_KEY_F25   				314
#define ABELIAN_KEY_KP_0   				320
#define ABELIAN_KEY_KP_1   				321
#define ABELIAN_KEY_KP_2   				322
#define ABELIAN_KEY_KP_3   				323
#define ABELIAN_KEY_KP_4   				324
#define ABELIAN_KEY_KP_5   				325
#define ABELIAN_KEY_KP_6   				326
#define ABELIAN_KEY_KP_7   				327
#define ABELIAN_KEY_KP_8   				328
#define ABELIAN_KEY_KP_9   				329
#define ABELIAN_KEY_KP_DECIMAL   		330
#define ABELIAN_KEY_KP_DIVIDE   		331
#define ABELIAN_KEY_KP_MULTIPLY   		332
#define ABELIAN_KEY_KP_SUBTRACT   		333
#define ABELIAN_KEY_KP_ADD   			334
#define ABELIAN_KEY_KP_ENTER   			335
#define ABELIAN_KEY_KP_EQUAL   			336	
#define ABELIAN_KEY_LEFT_SHIFT   		340
#define ABELIAN_KEY_LEFT_CONTROL   		341
#define ABELIAN_KEY_LEFT_ALT   			342
#define ABELIAN_KEY_LEFT_SUPER   		343
#define ABELIAN_KEY_RIGHT_SHIFT   		344
#define ABELIAN_KEY_RIGHT_CONTROL   	345
#define ABELIAN_KEY_RIGHT_ALT   		346
#define ABELIAN_KEY_RIGHT_SUPER   		347
#define ABELIAN_KEY_MENU   				348
#define ABELIAN_KEY_LAST   				ABELIAN_KEY_MENU